// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rankvhfyaelhtdhrcuqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhbmt2aGZ5YWVsaHRkaHJjdXF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTMwOTUsImV4cCI6MjA2NTI4OTA5NX0.kNtuaxNVLVQ4-aS72Nu2giA--dCW-njov9cggxZUF88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);